version: "3.4"

services:
    
    gym_php:
        image: php-es2:latest
        volumes:
            - type: bind
              source: ./
              target: /var/www/html
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                order: start-first
        networks:
            main:
                aliases:
                    - gym_php
    gym_nginx:
        image: nginx:1.11.8
        ports:
            - "8080:80"
        volumes:
            - type: bind
              source: .
              target: /var/www/html
            - type: bind
              source: ./logs
              target: /var/log/nginx/
            - type: bind
              source: ./nginx/default.conf
              target: /etc/nginx/conf.d/default.conf
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                delay: 15s
                parallelism: 1
                order: start-first
        networks:
            main:
                aliases:
                    - gym_nginx
    postgres:
        image: postgres:9.4
        ports:
            - 5432:5432
        volumes:
            -   type: bind
                source: ./data/postgresql
                target: /var/lib/postgresql/data
        networks:
            main:
                aliases:
                    - gym_postgres
networks:
    main:
        external: true
